# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-08 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_home', '0003_auto_20191108_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
