# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_home', '0004_auto_20191108_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cust_address',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cust_city',
            new_name='client_city',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cust_code',
            new_name='client_code',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cust_country',
            new_name='client_country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cust_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='vend_cust_code',
            new_name='vend_client_code',
        ),
    ]
