# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_home', '0005_auto_20191111_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterForClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_client_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilterForVendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_vend_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_desc', models.CharField(max_length=20)),
            ],
        ),
    ]
