# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_home', '0009_auto_20191125_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
