# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_user_home', '0010_auto_20191125_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user_name',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_second_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
