# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0003_auto_20191205_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
