# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-17 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0004_auto_20191205_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('input_date', models.DateField(auto_now_add=True)),
                ('vend_client_ind', models.CharField(max_length=1)),
                ('vend_client_code', models.CharField(blank=True, max_length=6)),
                ('user_id', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
