# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0005_featurecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
