# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0007_auto_20191218_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField()),
                ('client_code', models.CharField(blank=True, max_length=6)),
                ('user_id', models.CharField(max_length=10)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
