# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0008_featurepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepaid',
            name='author',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
