# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0009_featurepaid_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecomment',
            name='comments',
            field=models.CharField(max_length=300),
        ),
    ]
