# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-31 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4_features', '0010_auto_20191230_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='thumbs_up_count',
            new_name='client_count',
        ),
        migrations.RenameField(
            model_name='featurepaid',
            old_name='thumbs_up',
            new_name='quantity',
        ),
    ]
