# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterForClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_client_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilterForVendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_vend_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('client_code', models.CharField(blank=True, max_length=6)),
                ('user_name', models.CharField(max_length=50)),
                ('assigned_client_user', models.CharField(max_length=50)),
                ('assigned_vendor_user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(default='DRAFT', max_length=8)),
                ('progress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField(default=0)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('vend_client_ind', models.CharField(max_length=1)),
                ('vend_client_code', models.CharField(blank=True, max_length=6)),
                ('user_name', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
