# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterforclientuser',
            name='filter_client_desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='filterforvenduser',
            name='filter_vend_desc',
            field=models.CharField(max_length=50),
        ),
    ]
