# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0003_auto_20191111_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='input_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendorcomment',
            name='input_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
