# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0005_issue_software_component'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorComment',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='issue',
            name='details',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='issue',
            name='software_component',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
