# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-15 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0006_auto_20191114_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterForClient',
        ),
        migrations.DeleteModel(
            name='FilterForVendor',
        ),
        migrations.DeleteModel(
            name='StatusFilter',
        ),
    ]
