# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0007_auto_20191115_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
