# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0008_auto_20191121_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_client_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_vendor_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='details',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='issue',
            name='progress',
            field=models.CharField(default='Initial Input', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
