# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0009_auto_20191125_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='user_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
