# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0010_issue_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
