# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0011_auto_20191125_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_client_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_vendor_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
