# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0012_auto_20191125_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
