# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0013_auto_20191202_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
