# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0015_auto_20191204_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='progress',
        ),
    ]
