# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0016_remove_issue_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_client_user',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_vendor_user',
            field=models.CharField(max_length=10),
        ),
    ]
