# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0020_auto_20191216_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
