# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0021_issue_thumbs_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueThumbsUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField()),
                ('client_code', models.CharField(blank=True, max_length=6)),
                ('user_id', models.CharField(max_length=10)),
                ('thumbs_up', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='thumbs_up',
            new_name='thumbs_up_count',
        ),
    ]
