# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0022_auto_20191218_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuethumbsup',
            name='author',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
