# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0025_auto_20191230_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuecomment',
            name='comments',
            field=models.CharField(max_length=300),
        ),
    ]
