# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_issue_logging', '0026_auto_20191230_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
